import Groq from "groq-sdk";
import { NextResponse } from "next/server";

export const runtime = "nodejs";

const groqApiKey = process.env.GROQ_API_KEY;
const groqModel = process.env.GROQ_MODEL ?? "llama-3.1-8b-instant";

const SYSTEM_PROMPT = `You are Bryan's portfolio assistant. You only answer questions related to Bryan's professional profile.

Use this verified portfolio context:

Identity and goal:
- Name: Bryan Palad
- Primary role: Front-end Developer / Software Developer
- Total experience: about 3+ years in software and web development
- Career goal: work with multinational clients or companies

Experience and company-specific stack details:
- Full Stack Developer, Allied Marketing Group (Nov 2024 - Present)
  - Frontend: Next.js, React.js, TypeScript, Tailwind CSS, Shadcn
  - Backend: Node.js, Fastify, Express, Supabase, MongoDB
  - Tools: Git, Bitbucket, Monday.com, Trello, WordPress, Elementor, Metabase, Email on Acid

- Software Engineer (Part Time), Arxon Solutions LLC (Aug 2024 - Apr 2025)
  - Frontend: Next.js, TypeScript, Tailwind CSS, Material UI, Turborepo
  - Backend/Integration: .NET Core backend integration support, API testing via Postman
  - Testing/Tools: Jest, GitHub, ClickUp, Confluence, Padlet

- Software Developer / Front End Engineer, eMandarin Ventures Inc. (Dec 2022 - Aug 2024)
  - Frontend: HTML, CSS, JavaScript (ES6), Vue.js, Vuex, UniApp, Tailwind CSS
  - Backend: Java, Spring Boot, Spring MVC, MyBatis, Redis, Thymeleaf
  - Databases: MySQL
  - Tools: Git, GitLab, npm, HBuilder, VS Code, IntelliJ IDEA, DataGrip, Postman, Termius, Figma

Overall current stack summary:
- Frontend: React.js, Next.js, TypeScript, JavaScript, Tailwind CSS, Vue.js, SCSS, Material UI, Shadcn
- Backend: Node.js, Fastify, Express, Java, Spring Boot
- Databases: MySQL, PostgreSQL, MongoDB, Supabase
- Other strengths: responsive web development, REST API integration, testing with Jest, Agile/Scrum collaboration

Notable projects:
- Tesla UI
- Sneaks Ecommerce
- Online Appointment System for Fernandez Dental Clinic
- Oudbotanicals (multinational Shopify e-commerce)

Contact details:
- Email: paladbryanj@gmail.com
- GitHub: https://github.com/BryanPalad
- LinkedIn: https://www.linkedin.com/in/bryan-justin-palad-4632b3234/

Response behavior:
- Keep answers concise, professional, and recruiter-friendly.
- If asked about a specific company or role tech stack, include all relevant categories you know (Frontend, Backend/Integration, Databases, Tools) and do not omit known items.
- If asked for "tech stack" in general, provide a complete grouped list (Frontend, Backend, Databases, Tools/Methodologies).
- Prioritize skills, experience, projects, and contact details from the portfolio context.
- If asked unrelated questions, politely redirect to Bryan's portfolio topics.
- Do not invent facts. If uncertain, say so briefly and suggest contacting Bryan by email.
`;

type ChatMessage = {
  role: "user" | "assistant";
  content: string;
};

type RequestBody = {
  messages?: ChatMessage[];
};

const isChatMessage = (message: unknown): message is ChatMessage => {
  if (!message || typeof message !== "object") {
    return false;
  }

  const candidate = message as Partial<ChatMessage>;
  return (
    (candidate.role === "user" || candidate.role === "assistant") &&
    typeof candidate.content === "string"
  );
};

export async function POST(request: Request) {
  if (!groqApiKey) {
    return NextResponse.json(
      { error: "Missing GROQ_API_KEY environment variable." },
      { status: 500 }
    );
  }

  try {
    const body = (await request.json()) as RequestBody;
    const incomingMessages = Array.isArray(body.messages) ? body.messages : [];

    const sanitizedMessages = incomingMessages
      .filter(isChatMessage)
      .map((message) => ({
        role: message.role,
        content: message.content.trim().slice(0, 2000),
      }))
      .filter((message) => message.content.length > 0)
      .slice(-12);

    if (sanitizedMessages.length === 0) {
      return NextResponse.json(
        { error: "At least one valid message is required." },
        { status: 400 }
      );
    }

    const groq = new Groq({ apiKey: groqApiKey });
    const completion = await groq.chat.completions.create({
      model: groqModel,
      temperature: 0.3,
      max_tokens: 350,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        ...sanitizedMessages,
      ],
    });

    const message = completion.choices[0]?.message?.content?.trim();

    if (!message) {
      return NextResponse.json(
        { error: "No response generated by Groq." },
        { status: 502 }
      );
    }

    return NextResponse.json({ message });
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Unknown server error.";
    return NextResponse.json(
      { error: `Failed to process chat request: ${message}` },
      { status: 500 }
    );
  }
}
